version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PASS: $DATABASE_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: $POSTGRES_HOST_AUTH_METHOD
  migrations:
    build: .
    environment:
      PORT: 8000
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    environment:
      PORT: 8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - migrations
