version: '3'
services:
  db:
    image: postgres:12
    env_file:
      - ./wwcodesvtools/.env.dev.db
  migrations:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./wwcodesvtools/.env
    depends_on:
      - db
      - migrations
