name: FE-DEV-Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
    paths:
      - "frontend/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        env:
          CI: false
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
          npm test --silent -- --watchAll=false 
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wwcode-chtools-fe-dev"
          heroku_email: "sv@womenwhocode.com"
          appdir: "frontend"
          usedocker: true
          justlogin: true
      - name: "Login to heroku registry"
        run: heroku container:login
      - name: "Node version"
        run: node --version
      - name: "Build and push to heroku registry"
        run: >
          heroku container:push web
          --app wwcode-chtools-fe-dev
        env:
          REACT_APP_API_URL: https://wwcode-chtools-api-dev.herokuapp.com/api
      - name: "Releases the container"    
        run: heroku container:release web --app wwcode-chtools-fe-dev
